config:
  mon_type: icinga
icinga:
  prod:
    host: '192.168.5.160'
    port: '80'
    proto: 'http'
    auth_key: 'Z0ZcM7B4UOYfALLmLNhEdXkW5Ro'
#nagios:
#  prod:
#    url: 'http://my-prod-nagios/cgi-bin/nagios3/'
#    username: 'nagios'
#    password: 'nagios'
aviator:
  provider: openstack
  auth_service:
    name: identity
    host_uri: 'https://api1.example.com:5000'
    request: create_token
    validator: list_tenants
    api_version: v2
